### ISSUE TITLE
Make a test

### ISSUE THREAD

**Issue by moaeddy** [gentilkiwi/curveball#1]
would love to test this out, but don't think its good on windows and tried on kali seems not good also.

error on windows
```
altkey ..\public\CACA93B9D23D2B6FA76E8B8471931E0DF3EC6F63AF3CDBB936C41954A1872326.crt myprivate.key
[ERROR - BIO_read_filename]
2256:error:02001003:system library:fopen:No such process:crypto\bio\bss_file.c:288:fopen('..\public\CACA93B9D23D2B6FA76E8B8471931E0DF3EC6F63AF3CDBB936C41954A1872326.crt','rb')
2256:error:20074002:BIO routines:file_ctrl:system lib:crypto\bio\bss_file.c:290:
```

Error on kali
```
altkey ..\public\CACA93B9D23D2B6FA76E8B8471931E0DF3EC6F63AF3CDBB936C41954A1872326.crt myprivate.key
bash: altkey: command not found
```

Might sound noob, but a little put through will be appreciate

**Comment by gentilkiwi** [comment]
I saw this issue, and several ones you open everywhere.

I think you must be like...:
![image](https://user-images.githubusercontent.com/2307945/72763830-daa4bb80-3be5-11ea-96e1-107a9ebd8647.png)

**Comment by moaeddy** [comment]
Seriously? you are too perfect to give a dude hint. keep it up your awards awaits you
